name: Context with vars

on: 
 push:
 workflow_dispatch:
jobs:
 echo_data:
  runs-on: ubuntu-latest
  steps: 
   - name: Display Information
     run: |
      echo "Event name: ${{github.event_name}}"
      echo "Ref details: ${{github.ref}}"
      echo "SHA is: ${{github.sha}}"
      echo  "Actor is ${{github.actor}}"
      echo "Workflor is: ${{github.workflow}}"
      echo "Run ID is ${{github.run_id}}"
      echo "Runner is ${{github.run_number}}"
      echo " Runner is: ${{runner.os1}}"
   - name: Display Variable
     run: |
      echo "Variable ${{vars.MY_VAR}}"

      
      
