name: Run on diff O/S

on:
 push:
 workflow_dispatch:
jobs:
 echo-ubuntu:
  runs-on: ubuntu-latest
  steps:
   - run: echo "Run for $RUNNER_OS"
 echo-windows:
  runs-on: windows-latest
  steps:
   - run: echo "Run for $RUNNER_OS"
   
