name: Filters1

on:
 pull_request:
  branches:
  - master
 push: 
  paths-ignore:
   - 'README.md'
 

jobs:
 filters_echo:
  runs-on: Ubuntu-latest
  steps:
   - run: echo " Run whenever PR is opened or syn"
   
 
