name: functions

on:
 push:
 workflow_dispatch:
jobs:
 functions-concept:
  runs-on: ubuntu-latest
  steps:
   - name: Failing step
     run: exit 1
   - name: skipped step if previous is failed - Success step
     if: ${{success()}}
     run: echo "I will be printed if it is success"
   - name: Success if previous is failed
     if: ${{failure()}}
     run: echo "I will print if fail stt happend previous"
   - name: Cancel steps
     if: ${{cancelled()}}
     run: echo "Executes only if it is cancelled"
     
     
