name: matrix

on:
 workflow_dispatch:

jobs:
 matrix_echo:
  runs-on: ${{matrix.os}}
  strategy:
   matrix:
    node-version: [v22.6.0,v21.7.3]
    os:
     - ubuntu-latest
     - windows-latest
  steps:
   - uses: actions/setup-node@v4
     with:
        node-version: ${{matrix.node-version}}
   - name: Perform
     run: |
       echo "Matrix : ${{matrix.os}}"
       
