name: Simple API Request

on:
 push:
jobs:
 call-api:
  runs-on: ubuntu-latest
  steps:
   - name: Authentication API Request
     env: 
      API_KEY: ${{secrets.API_KEY}}
      run:
       echo "Authorization is $API_KEY"
       
      
     
 
